site_name: Acceso a Datos
site_url: http://sitename.example.com
theme:
  name: material
  font:
    text: Open Sans
    code: Red Hat Mono
  logo: ./assets/Cheste.png
  favicon: ./assets/Cheste.png
  features:
    - navigation.footer
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue grey
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
extra:
  social:
    - icon: simple/youtube
      link: https://youtube.com/@ciclosformativosinfo
    - icon: simple/bluesky
      link: https://bsky.app/profile/malsonvalencia.bsky.social
copyright: Copyright &copy; 2025 Manu Romero